### ISSUE TITLE
filtering hierarchy 

### ISSUE THREAD

**Issue by an5ir** [cubewise-code/tm1py-samples#33]
hi, i have a dimension animals, which contains  hierarchy animal. under animals there are element cat and dog. under cat there is a  separate element cat-owner and under dog element there is the element dog owner. so we have the following structure.

animals (dimension)
    - animals (hierarchy)
        - cat (element)
            - cat owner (element)
        - dog (element)
            - dog owner (element)
if i do
```
with TM1Service(**config['tm1srv01']) as tm1:
    dimension = tm1.dimensions.get(dimension_name=animals)
    hierarchy = dimension.hierarchies[0]

```
i get the entire animal hierarchy (i.e cat, cat owner, dog, dog owner).
is there some way to filter the hierarchy so i only get everything under cat only, so  cat, cat-owner ?

**Comment by an5ir** [comment]
Hi, thank that works great. 

However is there some way to get the edges between the elements as this produces a list of element. I need to know how the element are connected on the hierarchy. i.e the parent name of cat owner is cat.

**Comment by MariusWirtz** [comment]
Hi @an5ir ,

unfornutely not. TM1py does not yet have a function that gives you a slice of a dimension, including the relevant parent child relationships.

There are two things you can do now:
1. Query the entire hierarchy and then remove everything you don't need in python.
This code gives you all elements in the hierarchy and all parent-child relationships.
If your Hierarchy is < Members this is probably the best way to go. 

```
from TM1py import TM1Service

with TM1Service(address='10.77.19.60', port=12354, user='admin', password='apple', ssl=True) as tm1:
    hierarchy = tm1.dimensions.hierarchies.get(
        dimension_name="Date",
        hierarchy_name="Date")
    elements = hierarchy.elements
    edges = hierarchy.edges

```


2. Write a new function like `get_elements_and_edges_under_consolidation` that works similar to `get_members_under_consolidation`, but instead of the element names it returns elements and edges.
