### ISSUE TITLE
Is Single Sign on  possible in Tm1py

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py-samples#41]
I want to login into tm1 by single sign On is that possible please let me know if it possible

**Comment by MariusWirtz** [comment]
Yes. TM1py support SSO with CAM.

This what you need to provide in the config.ini. 
![image](https://user-images.githubusercontent.com/15182131/55428876-616ea600-558a-11e9-871e-7a5f428243d2.png)

If you want this feature, make sure you download TM1py from Github instead of PyPI. We have not drafted a release since a few weeks and the SSO is not yet included in the TM1py version on PyPI.
