### ISSUE TITLE
Element Create using ElementService module

### ISSUE THREAD

**Issue by wifi1677** [cubewise-code/tm1py-samples#45]
Hi,

I am try to add an element to the existing dimension by using `create(dimension_name, hierarchy_name, element)` from element service module. looks like element argument is an Element object of type class. when I call it as below:
```
from TM1py.Objects import ElementAttribute, Element

                dim = 'testing'
                element = Element(test1, 'NUMERIC')
                self.connection(address).dimensions.hierarchies.elements.create(
                    dim, dim, element)
```
Where Connection method is just to get a TM1session. 
I get the below response, Any idea what i am doing incorrect?
```
 File "/var/uber/python/lib/python3.6/site-packages/TM1py/Services/ElementService.py", line 23, in create
    return self._rest.POST(request, element.body)
  File "/var/uber/python/lib/python3.6/site-packages/TM1py/Services/RESTService.py", line 32, in wrapper
    self.verify_response(response=response)
  File "/var/uber/python/lib/python3.6/site-packages/TM1py/Services/RESTService.py", line 239, in verify_response
    raise TM1pyException(response.text, status_code=response.status_code, reason=response.reason)
TM1py.Exceptions.Exceptions.TM1pyException: Text: {"error":{"code":"278","message":"Invalid enum value encountered in payload."}} Status Code: 400 Reason: Bad Request
```
Can you add a sample usage for Element service module.
Thanks!

**Comment by MariusWirtz** [comment]
Hi @wifi1677 ,

this works for me:

``` python

from TM1py import TM1Service, Element

with TM1Service(address="10.77.19.10", port=12354, ssl=True, user="Admin", password="apple") as tm1:
    dimension_name = "dim1"
    element = Element(name="Elem125", element_type="STRING")

    tm1.dimensions.hierarchies.elements.create(
        dimension_name=dimension_name,
        hierarchy_name=dimension_name,
        element=element)

    hierarchy = tm1.dimensions.hierarchies.get(dimension_name=dimension_name, hierarchy_name=dimension_name)
    assert element.name in hierarchy
```

If you download the latest version of TM1py from Github your code should work fine. We wrote a fix early this year that fixes your problem: https://github.com/cubewise-code/tm1py/commit/09c9550b777ce3c30a9c46d1a25139c23ba63786

Before we wrote the fix you needed to specify `String`, `Numeric` or `Consolidated` in a way that the TM1 API would understand it. Meaning capitalized. Now in the current version TM1py manages the casing of the `element_type` correctly behind the scenes. So that users of TM1py don't need to bother with the casing.

The fix will be included in the next release. For the moment you can change the `element_type` in your code to `Consolidated `or download the latest version of  TM1py from GitHub

Cheers

Marius
