### ISSUE TITLE
Question about obtaining values

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py-samples#73]
Hello - Does anyone know if there is a way to check across cubes if specific dimension elements have data associated with them?  I am currently using MDX and querying cubes at all top levels except the dimension with elements in question and creating a subset off the returned elements with a value of 0.  I then use this subset to drill into a suppressed view and expanded time dimension and and account dimension where there are potential reversals to get the real set.  It's do-able but just wondering if there may be a quicker or faster way, or if it would be a possible enhancement feature.  We have multiple dimensions with 2+ million elements, many we now have no data but trying to do anything in perspectives with that size is impossible.  What I am doing is not the most efficient but works.  Has anyone done something similar?  I would imagine it could be beneficial to have a way to cleanup unused elements in a dimension when working with large models.
Thanks!

**Comment by MariusWirtz** [comment]
Hi @jbeanz23,

I think your second step:
> I then use this subset to drill into a suppressed view and expanded time dimension and and account dimension where there are potential reversals to get the real set

 wouldn't be necessary, if you had clean `TOTAL` consolidations in every dimension.

What are the limitations of your current approach? - is it too slow or overly complex code-wise?

In my previous project, we had exactly the same problem.
The overly large dimensions (> 1M leaves) were slowing the users down in their daily work.

After we noticed that only roughly half of the leaf elements actually had data associated with them, we implemented a clean-up job that would run regularly and remove "obsolete elements".
We used a similar approach that you are describing:

For n cubes, we would execute MDX queries that have all leaves of the dimension in-question on the rows, and the total elements of all other dimensions on the columns.
Then we would know for each cube, which elements are empty.
Then we would intersect the result sets from the cubes. The result is the elements that can safely be removed.

In order to speed it up we did two things:
- parallelize the MDX executions against the different cubes
- delete the obsolete elements with TI. Python would create a subset with the obsolete elements and would then execute a process that deletes the elements from the dimension.

**Comment by jbeanz23** [comment]
Sorry for the delay.  That is what we are currently doing though we have not got to the deletion of obsolete elements.  We do have one of the region specific dimensions that does have multiple (15K) consolidations so that may be an issue but we have not started on that one yet
